services:
  - type: web
    name: recycle-form
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: DATABASE_URL
        value: sqlite:///data.db
